# Exercise.create(name: "Squat", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Quads", long_description: "more detail here", img_url: "img.com")
# Exercise.create(name: "Deadlift", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Back", long_description: "more detail here", img_url: "img.com")
# Exercise.create(name: "Bench Press", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Chest", long_description: "more detail here", img_url: "img.com")
# Exercise.create(name: "Militray Press", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Shoulders", long_description: "more detail here", img_url: "img.com")
# Exercise.create(name: "Pull Ups", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Back", long_description: "more detail here", img_url: "img.com")
# Exercise.create(name: "Romanian Deadlift", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Hamstring", long_description: "more detail here", img_url: "img.com")

Program.create(name: "Program 1")
Program.create(name: "Program 2")
Program.create(name: "Program 3")

Day.create(name: "Push", program_id: 1)
Day.create(name: "Pull", program_id: 1)
Day.create(name: "Legs", program_id: 1)
Day.create(name: "Upper", program_id: 2)
Day.create(name: "Lower", program_id: 2)
Day.create(name: "Full Body", program_id: 3)
