Exercise.create(name: "Squat", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Quads", long_description: "more detail here", img_url: "img.com")
Exercise.create(name: "Deadlift", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Back", long_description: "more detail here", img_url: "img.com")
Exercise.create(name: "Bench Press", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Chest", long_description: "more detail here", img_url: "img.com")
Exercise.create(name: "Militray Press", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Shoulders", long_description: "more detail here", img_url: "img.com")
Exercise.create(name: "Pull Ups", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Back", long_description: "more detail here", img_url: "img.com")
Exercise.create(name: "Romanian Deadlift", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Hamstring", long_description: "more detail here", img_url: "img.com")
