# Exercise.create(name: "Squat", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Quads", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Deadlift", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Back", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Bench Press", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Chest", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Militray Press", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Shoulders", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Pull Ups", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Back", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Romanian Deadlift", volume: "3 sets 5-8 reps", short_description: "Primary muscle targeted Hamstring", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Tricep Pushdown", volume: "3 sets 10-15 reps", short_description: "Triceps", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Bicep Curl", volume: "3 sets 10-15 reps", short_description: "Biceps", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Lateral Raise", volume: "3 sets 10-15 reps", short_description: "Side Delts", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Lat Pull Down", volume: "3 sets 10-15 reps", short_description: "Lats", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Calve Raise", volume: "3 sets 5-8 reps", short_description: "Calves", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Hip Thrust", volume: "3 sets 8-12 reps", short_description: "Glutes", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Leg Press", volume: "3 sets 10-15 reps", short_description: "Quadriceps", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Leg Curl", volume: "3 sets 10-15 reps", short_description: "Hamstrings", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Dumbbell Shoulder Press", volume: "3 sets 8-12 reps", short_description: "Shoulders", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Dumbbell Bench Press", volume: "3 sets 8-12 reps", short_description: "Chest", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")
# Exercise.create(name: "Leg Extension", volume: "3 sets 10-15 reps", short_description: "Quadriceps", long_description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.", img_url: "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?q=80&w=1000&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8Z3ltfGVufDB8fDB8fHww")

# Tag.create(name: "Compound")
# Tag.create(name: "Accessory")
# Tag.create(name: "Upper Body")
# Tag.create(name: "Lower Body")
# Tag.create(name: "Front Delts")
# Tag.create(name: "Side Delts")
# Tag.create(name: "Rear Delts")
# Tag.create(name: "Chest")
# Tag.create(name: "Back")
# Tag.create(name: "Triceps")
# Tag.create(name: "Biceps")
# Tag.create(name: "Quadriceps")
# Tag.create(name: "Hamstrings")
# Tag.create(name: "Calves")
# Tag.create(name: "Glutes")
# Tag.create(name: "Lats")
# Tag.create(name: "Traps (trapezius)")
# Tag.create(name: "Abdominals")

# ExerciseTag.create(tag_id: 1, exercise_id: 1)
# ExerciseTag.create(tag_id: 1, exercise_id: 2)
# ExerciseTag.create(tag_id: 1, exercise_id: 3)
# ExerciseTag.create(tag_id: 1, exercise_id: 4)
# ExerciseTag.create(tag_id: 1, exercise_id: 6)
# ExerciseTag.create(tag_id: 1, exercise_id: 14)
# ExerciseTag.create(tag_id: 2, exercise_id: 5)
# ExerciseTag.create(tag_id: 2, exercise_id: 8)
# ExerciseTag.create(tag_id: 2, exercise_id: 9)
# ExerciseTag.create(tag_id: 2, exercise_id: 10)
# ExerciseTag.create(tag_id: 2, exercise_id: 11)
# ExerciseTag.create(tag_id: 2, exercise_id: 12)
# ExerciseTag.create(tag_id: 2, exercise_id: 13)
# ExerciseTag.create(tag_id: 2, exercise_id: 15)
# ExerciseTag.create(tag_id: 2, exercise_id: 16)
# ExerciseTag.create(tag_id: 2, exercise_id: 17)
# ExerciseTag.create(tag_id: 2, exercise_id: 18)
# ExerciseTag.create(tag_id: 2, exercise_id: 19)
# ExerciseTag.create(tag_id: 3, exercise_id: 3)
# ExerciseTag.create(tag_id: 3, exercise_id: 4)
# ExerciseTag.create(tag_id: 3, exercise_id: 5)
# ExerciseTag.create(tag_id: 3, exercise_id: 8)
# ExerciseTag.create(tag_id: 3, exercise_id: 9)
# ExerciseTag.create(tag_id: 3, exercise_id: 10)
# ExerciseTag.create(tag_id: 3, exercise_id: 11)
# ExerciseTag.create(tag_id: 3, exercise_id: 12)
# ExerciseTag.create(tag_id: 3, exercise_id: 17)
# ExerciseTag.create(tag_id: 3, exercise_id: 18)
# ExerciseTag.create(tag_id: 4, exercise_id: 1)
# ExerciseTag.create(tag_id: 4, exercise_id: 6)
# ExerciseTag.create(tag_id: 4, exercise_id: 13)
# ExerciseTag.create(tag_id: 4, exercise_id: 14)
# ExerciseTag.create(tag_id: 4, exercise_id: 15)
# ExerciseTag.create(tag_id: 4, exercise_id: 16)
# ExerciseTag.create(tag_id: 4, exercise_id: 19)
# ExerciseTag.create(tag_id: 5, exercise_id: 4)
# ExerciseTag.create(tag_id: 5, exercise_id: 17)
# ExerciseTag.create(tag_id: 6, exercise_id: 11)
# ExerciseTag.create(tag_id: 8, exercise_id: 3)
# ExerciseTag.create(tag_id: 8, exercise_id: 18)
# ExerciseTag.create(tag_id: 9, exercise_id: 2)
# ExerciseTag.create(tag_id: 9, exercise_id: 5)
# ExerciseTag.create(tag_id: 9, exercise_id: 6)
# ExerciseTag.create(tag_id: 9, exercise_id: 8)
# ExerciseTag.create(tag_id: 9, exercise_id: 12)
# ExerciseTag.create(tag_id: 10, exercise_id: 3)
# ExerciseTag.create(tag_id: 10, exercise_id: 9)
# ExerciseTag.create(tag_id: 11, exercise_id: 8)
# ExerciseTag.create(tag_id: 11, exercise_id: 10)
# ExerciseTag.create(tag_id: 12, exercise_id: 1)
# ExerciseTag.create(tag_id: 12, exercise_id: 15)
# ExerciseTag.create(tag_id: 12, exercise_id: 19)
# ExerciseTag.create(tag_id: 13, exercise_id: 2)
# ExerciseTag.create(tag_id: 13, exercise_id: 6)
# ExerciseTag.create(tag_id: 13, exercise_id: 16)
# ExerciseTag.create(tag_id: 14, exercise_id: 13)
# ExerciseTag.create(tag_id: 15, exercise_id: 1)
# ExerciseTag.create(tag_id: 15, exercise_id: 14)
# ExerciseTag.create(tag_id: 15, exercise_id: 15)
# ExerciseTag.create(tag_id: 16, exercise_id: 12)

# Program.create(name: "Program 1")
# Program.create(name: "Program 2")
# Program.create(name: "Program 3")

# Day.create(name: "Push", program_id: 1)
# Day.create(name: "Pull", program_id: 1)
# Day.create(name: "Legs", program_id: 1)
# Day.create(name: "Upper", program_id: 2)
# Day.create(name: "Lower", program_id: 2)
# Day.create(name: "Full Body", program_id: 3)

# ExerciseDay.create(exercise_id: 3, day_id: 1)
# ExerciseDay.create(exercise_id: 4, day_id: 1)
# ExerciseDay.create(exercise_id: 5, day_id: 2)
# ExerciseDay.create(exercise_id: 6, day_id: 2)
# ExerciseDay.create(exercise_id: 1, day_id: 3)
# ExerciseDay.create(exercise_id: 3, day_id: 4)
# ExerciseDay.create(exercise_id: 5, day_id: 4)
# ExerciseDay.create(exercise_id: 1, day_id: 5)
# ExerciseDay.create(exercise_id: 6, day_id: 5)
# ExerciseDay.create(exercise_id: 1, day_id: 6)
# ExerciseDay.create(exercise_id: 2, day_id: 6)
# ExerciseDay.create(exercise_id: 3, day_id: 6)
# ExerciseDay.create(exercise_id: 5, day_id: 6)
